---
- name: Install nginx, spring-boot-apps
  hosts: all
  # remote_user: root
  remote_user: user
  become: yes
  become_method: sudo

  roles:
    - nginx
    - spring-boot-app
    
 - name: Check apps is up
  hosts: apps
  become: yes
  become_method: sudo
  tasks:
    - uri:
        url: "http://{{ apps_ip4_address }}:8080"
        method: GET
      register: check
      until: "'OK' in check.msg"
      retries: 10
      delay: 30
      ignore_errors: true
      when: apps_is_primary == true

